version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: co2_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: co2_emissions
      POSTGRES_USER: co2user
      POSTGRES_PASSWORD: co2password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      - co2_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U co2user -d co2_emissions"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  co2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16